Repository sern-handler/cli, pull requests merged in 2022-05, with the labels that each got.

#19 feat: add default settings for the -y flag
  src/commands/init.js
  src/prompts/init.js
  src/utilities/npm.js
Labels: Enhancement

#24 fix: no more crashing cli if yarn isnt present
  .gitignore
  src/commands/init.js
  src/utilities/npm.js
Labels: Sem: Patch, Bug Fix

#20 feat(skip): option to skip package manager selection
  src/commands/init.js
  src/prompts/init.js
  src/utilities/install.js
Labels: Enhancement

#25 feat: Added version command & created readme
  README.md
  src/commands/help.js
  src/index.js
  src/utilities/version.js
Labels: Documentation, Enhancement
